CREATE TABLE lmt_queue (
 id INT PRIMARY KEY,
 lniata VARCHAR(50) NOT NULL,
 state VARCHAR(50) NOT NULL,
 head_id INT,
 tail_id INT
--  created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
--  updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE lmt_queue_element (
 id UUID PRIMARY KEY,
 lniata INT NOT NULL,
 data VARCHAR(255),
 previous_id UUID,
 next_id UUID
--  created_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
--  updated_at TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);